development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://sbzzgeswkutuwr:b621dc2b4df6155b36805569e5bb1e3f259abf542d368ef395e1f08879335c4b@ec2-23-21-220-188.compute-1.amazonaws.com:5432/dautedv6eetvcm
  channel_prefix: app1_production
